// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: bookmarks.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBookmark = `-- name: DeleteBookmark :execrows
DELETE FROM bookmarks
WHERE id = $1
`

func (q *Queries) DeleteBookmark(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBookmark, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBookmark = `-- name: GetBookmark :one
SELECT id, url, title, tags, created_at
FROM bookmarks
WHERE id = $1
`

func (q *Queries) GetBookmark(ctx context.Context, id string) (Bookmark, error) {
	row := q.db.QueryRow(ctx, getBookmark, id)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Tags,
		&i.CreatedAt,
	)
	return i, err
}

const insertBookmark = `-- name: InsertBookmark :exec
INSERT INTO bookmarks (id, url, title, tags, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertBookmarkParams struct {
	ID        string
	Url       string
	Title     string
	Tags      []string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertBookmark(ctx context.Context, arg InsertBookmarkParams) error {
	_, err := q.db.Exec(ctx, insertBookmark,
		arg.ID,
		arg.Url,
		arg.Title,
		arg.Tags,
		arg.CreatedAt,
	)
	return err
}

const searchBookmarks = `-- name: SearchBookmarks :many
SELECT id, url, title, tags, created_at
FROM bookmarks
WHERE
    ($1::text = '' OR title ILIKE '%' || $1 || '%' OR url ILIKE '%' || $1 || '%')
    AND ($2::text = '' OR $2 = ANY (tags))
ORDER BY created_at DESC, id ASC
`

type SearchBookmarksParams struct {
	QueryText string
	Tag       string
}

func (q *Queries) SearchBookmarks(ctx context.Context, arg SearchBookmarksParams) ([]Bookmark, error) {
	rows, err := q.db.Query(ctx, searchBookmarks, arg.QueryText, arg.Tag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bookmark{}
	for rows.Next() {
		var i Bookmark
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.Tags,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
