// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bookmark struct {
	ID        string
	Url       string
	Title     string
	Tags      []string
	CreatedAt pgtype.Timestamptz
}
